### ISSUE TITLE
Attempt to use natural language for search fails when translating to other language

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#189] opened 2020-05-22 13:46 UTC
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x ] Did you choose a good title?

**Describe the bug**

When trying an extended search a certain formal construction of the search string must be observed: `property comparison value` otherwise the QMS search code can't parse the phrase properly. When using an English QMS version search strings are close to good English phrases and can be parsed easily: Example from the latest update of language files: `status is available`. The phrase is good English, and it matches the formal construction rule, too. All three words can be found in the list of feasible words for property/comparison/value.

Trying to translate this easy phrase as a natural language phrase to Russian causes several conflicts: the normal translation of "is" to Russian is "" (just nothing). But "" can't be a comparison operator in the formal search string. Other translations with other verbs are possible but less frequent and lead to the next conflict: the (translation of the) word "available" in the value position of the search string is fixed and can't be changed with declination/conjugation endings. But the use of natural language in Russian requires some change of the suffix/ending of the word (and the Russian user will certainly automatically follow his well-known grammar rules). But with this suffix the value part of the search string can't be recognized by the code anymore. I'm not sure, if such a situation could also happen with German search strings.

Using a formal construction on the other hand would need some special markers (e.g. '"') to make it obvious to the user that the search string is a formal construct composed of words from three given lists and not a natural language phrase and that therefore grammar rules don't apply. 

**What have you done to circle down the problem?**

Checked with various relevant messages in language file.

**To Reproduce**

Try to translate "status is available" to Russian and stick to natural language while using given translation of "available", too.

**Expected behavior**

Add to the search help window and to the Wiki a clear warning "property, comparison, and some "value" entries (e.g. status of a geocache) must be taken from given lists irrespective of grammar rules (violation)". 

Wrt. "value" part: a list must be added to the help window giving those entries which must have a fixed form (e.g. the possible status values of a geocache - the user can't guess them or more precisely, can't guess the necessary ending/suffix to be used! English speakers are lucky: they rarely use such suffixes.)

This proposal might also need some re-organization of the search help window. Already now it is rather big with plenty of necessary information. Listboxes with transfer of the selected word to the edit field?

**Screenshots**

None

**Attachments**

Not necessary

**Tracebacks**

Not necessary

**Desktop (please complete the following information):**

QMS with language having lots of declination/conjugation endings

**Additional context**

None

**Comment by kiozen** [comment] 2020-05-22 13:57
@pingurus please have a look!

**Comment by pingurus** [comment] 2020-05-22 17:09
Simple things first:

> Wrt. "value" part: a list must be added to the help window giving those entries which must have a fixed form (e.g. the possible status values of a geocache - the user can't guess them or more precisely, can't guess the necessary ending/suffix to be used! English speakers are lucky: they rarely use such suffixes.)

There is a tooltip for those properties with fixed values stating the possible values.

And now to the core problem:

Is there a word order in russian that can be used as reliably as `property value comparison` in russian (and that there is an 'is' comparator)? Then I maybe could tweak the code to make the word order language dependent (but consistent within the language).

If, however, russian is like hungarian in that respect, I guess it won't work having these three keyword structure. If we move to some tree based approach that can be translated and adapted to each language (would have to read qt documentation + think about it), having word completion could be a nice side-effect. But that would require rewriting the code and could take some time. I would (maybe) be interested in doing it though.

**Comment by wthaem** [comment] 2020-05-22 18:45
> There is a tooltip for those properties with fixed values stating the possible values.

Not sure, if a user understands that he is obliged to use exactly the words from the tooltip list as values.

> Is there a word order in russian that can be used as reliably ...

No. Having the suffixes it is easy to distinguish a subject from an object. Thus, no strict subject - predicate - object rule.

My feeling is, that a change of the parser would be too much of a good thing. You spend a lot of effort and time for a few users having a few special search queries. 

What I have in mind are better ways to inform the user (or at the best to force him) what he has to do when formulating a search query and what he can't do. 

For English speaking users this seems to be a minor problem. But for other languages it starts as described with the translation process: the translator gets a series of messages without much information - if any - what the relation between the messages might be. Thus, coherance can be lost already during translation. Example: there is a message with the single word "Available". Translation is easy. And then this same and very wildly used word appears in some tooltip. And there the difficulty starts: status requires the Russian form "доступен", but I would the single word "Available"  as "доступно". In connection with the verb "is" the form could even be "доступным". And here you can even see that the words "suffix/ending" must be used with care.

**Comment by pingurus** [comment] 2020-05-22 19:01
The help window alread states the syntax. If you feel that clarification is needed for russian-speaking users, feel free to edit the help window text. Are there other ways you have in mind to inform the user?

If the "property comparison value" can somehow be used in russian, I'd prefer to leave it as is, words that can't be translated sensibly could just be translated as "", then I'd add code to remove those entries. 

The users already gets feedback if the parser does not understand the query, I'm not sure how one could 'force him' without losing the intentional freedom of the search.

**Comment by wthaem** [comment] 2020-05-23 07:43
> The help window already states the syntax.

That's correct. But I think there are 2 weaknesses or bottlenecks:

* The user has not only to follow the syntax, but also use in certain queries value entries from a predefined list and exactly as they are given in this list. And this must be made more explicit.
* The user has to be informed that following the syntax can violate grammar rules.

> If you feel that clarification is needed for russian-speaking users, feel free to edit the help window text. 

It is not a problem of Russian-speaking users (even if they might be concerned most). The help window is used in any language supported by QMS. The content (text) of the help window is a translation of the English version of the text defined in the code.  I never would be in favor of additional text parts appearing only in one language. Thus any additional text must be available in all languages. And this leads to the next problem: Already now, the text in the help window is extremely long. Adding more needs certainly a better structure and an improved presentation of the text (use of tabs in the window?). And this may imply some work with QtDesigner and the code behind the window.


> The users already gets feedback if the parser does not understand the query,

That is correct, too. But the currently used information similar to "Syntax error!" (if given!) is not really helpful when trying to remove the error in the query. And there is more: take, as an example a German QMS and use the search query "status = grün". The syntax is correct. The value part is wrong. It is not taken from the list of feasible values. No error message is shown, most likely the query is silently considered as a full text search. Forget your knowledge of the code and try to understand this! A similar example using the Russian version gives the same result but due to the grammar problem there it is much more serious than the simple German example where the error is more or less obvious.

**Comment by pingurus** [comment] 2020-05-23 08:07
> It is not a problem of Russian-speaking users (even if they might be concerned most). The help window is used in any language supported by QMS. The content (text) of the help window is a translation of the English version of the text defined in the code. I never would be in favor of additional text parts appearing only in one language. Thus any additional text must be available in all languages.

Sure. Maybe there was a misunderstanding, I meant it in the way that we adapt the english original in a way that the translations cover also the issues that may appear in other languages including russian.

> Already now, the text in the help window is extremely long. Adding more needs certainly a better structure and an improved presentation of the text (use of tabs in the window?). And this may imply some work with QtDesigner and the code behind the window.

Since I wrote the code I most probably don't have a feeling for the issues a user has who has no idea of the code. I think it would be most effective if you supply me with the layout and contents of the help window that you have in mind and meets the need of the users and I will then implement it.

> And there is more: take, as an example a German QMS and use the search query "status = grün". The syntax is correct. The value part is wrong. It is not taken from the list of feasible values. No error message is shown, most likely the query is silently considered as a full text search. 

Good catch! It is simply trying to find "grün" as a status, which will not appear in any geocache. Writing the code to catch those errors should not be too hard with the current code.

> A similar example using the Russian version gives the same result but due to the grammar problem there it is much more serious than the simple German example where the error is more or less obvious.

What is the solution you wish to remove the problems appearing in russian? As I said before, if it is a redesign of the help window, go ahead and provide me with something i can implement. I will try to help where I can and understand the issues (and I certainly see that there are some), but I do not know (especially with regard to russian grammar) how I should edit the help window to make it easier for the user to understand.

**Comment by wthaem** [comment] 2020-05-23 09:47
Ok. I'll try. But this will take some time.

**Comment by mitxel-m** [comment] 2020-05-25 11:12
Hi @wthaem 
I faced similar problems when I made the Spanish translation for the Search help, but in the case of Spanish it was related to the concordance of the property and comparison genre, as in Spanish the word genre is is usually marked with a suffix... I guess that it will be similar for other latin languages like French.

Fortunately, I managed to solve the problem by significantly reducing the list of comparison terms, and using only a few generics that work for all genres.

This was done in the translation file by remapping several comparison terms to a single non-gender term instead of doing a literal translation. This has resulted in the list of comparison terms in Spanish being much smaller and easier to handle by the user than the original, but with the same functionality. 

I also added a comment on the translation, warning future translators of the reason not to make a literal translation.

It is important to note that the original comparison terms that have been remapped are not repeated in the translated list. This is a screenshot:

![Search_Help_Spanish_screenshot](https://i.ibb.co/kMPxxCB/QMS-SEARCH-Ayuda.jpg)

I don't know if something like this can be done for other translations. Maybe remapping in the translation 'is' to '=' could be a workaround for the Russian translation, since the user will see it more as a formula than as natural language.

**Comment by wthaem** [comment] 2020-05-25 16:17
@mitxel-m: Thanks for your remarks! My guess was, that other translators could have had language trouble, too. And now you confirmed this for the Spanish language.

Me too, I had the idea to reduce radically the lists of synonyms in order to cope with this situation, but I didn't do it (yet). This reduction would be just opposite to the code author's intention to give the user as much ways as possible to formulate a search query or, as I formulated it earlier in this thread, to be as close to natural language as possible with search queries. In principle, a good idea but it brings in (natural) language dependency in a software used in several languages.

**Comment by wthaem** [comment] 2020-05-26 11:08
**Remarks about current state of the search help window:**

* Detailed information is necessary when composing an extended search string. This information should be given in the QMS GUI language, Therefore, the Wiki information, which is in English only, is not sufficient. Some kind of a QMS help window must be used to provide help.
* Currently, the help window is filled with plenty of information. Scrolling in the window can't be avoided. Some information is provided in form of tooltips. Thus, it seems natural to think about a re-organization of the presentation of the search help information.

**Proposal for a new layout structure of the search help window:**

* Use a tab widget with 3 tabs (compare attached ui file):
    * Tab **General introduction**: All the (slightly updated) text without the keyword and comparison operators lists taken from the current window.
    * Tab **Examples**: All the examples provided as tooltips. Maybe, a table view can make the structure of the search strings more obvious.
    * Tab **Search string composer**: 3 comboboxes for the selection of the 3 query parts `keyword, comparison operator` and `value`. Maybe, additionally an edit field showing the complete selected search string.
    
**Additional features:**

* It shouldn't be too hard to implement some logic in the third tab:
    * Activate comboboxes for comparison and value only after selection of a keyword.
    * When activating the comparison operator combobox, then show only those operators which can be used with the selected keyword.
    * When activating the value combobox, then show only feasible values (e.g. for geocache status) of this field or feasible templates (e.g. date template) for the selected keyword and operator. Allow the user to edit a value template. The edit field could show the complete search string and could be used to point to possible errors in the string.
    * Use a button to transfer the selected values of the 3 comboboxes as search string to the QMS search edit field (and start the search?).
* Would it be possible and reasonable to allow the selection of an example in the examples tab as a template for a search string and allow editing of this string?   
* The help window should have a "Help" button. Clicking it should open the Wiki page which describes the extended search. Could this be the first case in QMS where not the Wiki page but the same page in the F1/Qt help window could be displayed? 


*Remember, this is a proposal for discussion!*

[QueryComposer.zip](https://github.com/Maproom/qmapshack/files/4681726/QueryComposer.zip)

**Comment by pingurus** [comment] 2020-05-27 12:27
In general I think your idea is good.

>When activating the value combobox, then show only feasible values (e.g. for geocache status) of this field or feasible templates (e.g. date template) for the selected keyword and operator. Allow the user to edit a value template. The edit field could show the complete search string and could be used to point to possible errors in the string.
Use a button to transfer the selected values of the 3 comboboxes as search string to the QMS search edit field (and start the search?).

This however is not possible by design, since any operator can be used on any property if a `GisItem` returns a value that the operator can compare. Same goes for 'possible' values. For example a query `size equals nano` may be an 'invalid' query for geocaching.com geocaches, but who knows, maybe some other geocaching service may have that size. 

The code does not know what queries are valid. After extracting the property, comparator and the value from the string, all it does is:
```
For each GisItem in the project do:
    get the value of the property of the GisItem. 
        The GisItem may return up to two floats and two strings
    plug both the value the user specified and the value of the GisItem into the comparator
    if the comparison is true, show the item, if not not.
```

The GisItem checks by itself wether it has the property or not and if not it will simply return an empty value. An empty value will always hide the GisItem.

The intention was to make it easy to add new properties and comparators without having to adjust the code in too many places. I am sure that this can be refactored into some kind of tree to fulfill your wishes, but it would take time to implement.

If you have any questions about the inner workings to find out what would be possible to do, just go ahead and ask :smile:

**Comment by wthaem** [comment] 2020-05-27 17:40
Remember the title of this thread: it is primarily a language/translation problem which we are discussing here. I intentionally didn't mention it in my last proposal because I expected a reduction of the translation difficulties with the proposed behavior of the comparison and the value comboboxes. With your description of the code behind the search string this expectation fails. I wouldn't go in the direction of bigger code changes!

Once I don't know a better solution, I am inclined to be in favor of Mitxel's approach: Use the translation to reduce the number of synonyms for operators and, maybe, keywords, too. Leave only those operators and keywords that lead to a more or less appropriate translation of the complete search strings. This doesn't reduce the searches that can be formulated. It reduces only the degree of freedom when formulating the queries. Not exactly a good approach because with this the translator is going to change the coding philosophy.

When following this approach there is no more need to change the structure of the help window. A single phrase "The keyword and compare operator lists depend on the QMS GUI language used." is all what should be added to the help text.

**Comment by mitxel-m** [comment] 2020-05-28 11:43
__Regarding terms and comparators:__

In my opinion the approach of reducing terms and comparators does not contradict the intention to use natural language. In the case of Spanish it has been a good solution. It narrows the catalogue of terms, but this also has a positive part for the user, since it is easier to remember.

The feature of non-repeating terms in the list is a very well done thing in pingurus' development, so why not take advantage of it when it is convenient?

Personally I assume it is almost impossible to make a development that would fit fine for all languages. Example: in Basque, the grammatical form is property-value-comparison, and in some cases the comparison is not a term but a suffix added to the value, so a translator would find impossible to use the natural language in the current development (don't worry, I'm not planning to add the Basque translation, it's just an example).  However, the user can adapt to the property-comparison-value form assumming that it is used as a formula because in everyday life we are already used to this kind of notation. 

Currently many comparators in the long list can be "shortcutted" with the symbols `<` `>` and `=` . I use them frequently because it is faster to type `>` instead of `higher than` or `after` . The only ones not replaceable by `<` `>` and `=` would be `with` `without` `between`. It would be a good idea to add their synonym as symbols like `+`, `-`, and `<>` respectively.
 
Examples :
 
- `description - glacier` instead of `description without glacier`. 
- `Data <> 20190/05/28 and 2020/05/28` instead of `Data between 20190/05/28 and 2020/05/28`

This could be very helpful for cases where it is difficult to reproduce natural language within the current development, and also to be used as shortcuts by all users. This would not be an intrusive change, just add three new comparators to the list.

I also find faster typping `>` because while I start typing `higher than` the search engine is already trying to search it as a string (simple search) before using it as a comparator.

__Regarding the search help text:__

It would be good to add:

_The dot (.) is used as a decimal separator_

right after the unit list.

__Regarding the search help dialogue:__

I find that it always keeps the focus above the rest of the windows, even windows from other applications. I've been checking the dialogue with Qt-Designer but I haven't found the key to avoid it.
I don't know if this is intentional in the development.

**Comment by pingurus** [comment] 2020-05-28 11:58
> The feature of non-repeating terms in the list is a very well done thing in pingurus' development, so why not take advantage of it when it is convenient?

I can't remember doing that intentionally, but I agree it comes handy now :laughing: 

> It would be a good idea to add their synonym as symbols like +, -, and <> respectively.

Sure, matter of 5 minutes

> I also find faster typping > because while I start typing higher than the search engine is already trying to search it as a string (simple search) before using it as a comparator.

This should be already fixed in current dev

> I find that it always keeps the focus above the rest of the windows, even windows from other applications. I've been checking the dialogue with Qt-Designer but I haven't found the key to avoid it.
I don't know if this is intentional in the development.

If I recall it correctly, this was the only way to make sure the window stays in front of the main QMS window.

### Current whished changes to the help window:

* The point ( . ) is used as decimal separator
    * I have to check wether this is fied or locale dependent
* The keyword and compare operator lists depend on the QMS GUI language used.

Any more I missed?

**Comment by kiozen** [comment] 2021-01-16 10:48
Seems to be a stalled ticket. I close it for now.

**Closed by kiozen** 2021-01-16 10:48 UTC
Labels: bug
