### ISSUE TITLE
Geo search hidden after restarting QMapShack

### ISSUE THREAD

**Issue by googol42** [Maproom/qmapshack#89] opened 2020-01-03 11:42 UTC
**Describe the bug**
The geo search is disabled after each restart of QMapShack despite the menu entry being enabled.

**To Reproduce**
1. Open QMapShack
2. Enable the geo search (→ a geo search "project" is created →everything as expected until now)
3. Enable a large map (I enabled a map *over 3 GB and I don't have a SSD*).
4. Close QMapShack and start it again. *The bug will only be triggered, when the dialog with the map loading information appears while the splash is shown.*
5- Now the geo search is not visible but the menu entry is enabled (see screenshots).

To enable it I have to disable the menu entry and enable it again

**Expected behavior**
- the geo search should be displayed when the setting is enabled

**Screenshots**
![screeni1](https://user-images.githubusercontent.com/9155562/71721658-2b669700-2e26-11ea-82ed-39c9d5d0eb9b.png)
![screeni2](https://user-images.githubusercontent.com/9155562/71721660-2d305a80-2e26-11ea-9f25-9ec149961b74.png)

**Desktop:**
 - ArchLinux 5.4.7-arch1-1 with i3
 - QMapShack 1.14.0

**Comment by kiozen** [comment] 2020-01-03 12:06
I can't reproduce the bug. Anyone else?

**Comment by googol42** [comment] 2020-01-03 12:17
Do you need more information?

**Comment by pingurus** [comment] 2020-01-03 14:04
Can't reproduce it either.

**Comment by anesthesia79** [comment] 2020-01-04 11:16
Can't reproduce on my system.

OS: Linux Mint 19.3
QMS: latest commit

**Comment by kiozen** [comment] 2020-01-07 17:44
How do we want to proceed? Are there any other details to trigger the problem?

**Comment by googol42** [comment] 2020-01-07 17:58
@kiozen I played around a bit and suddenly it does not disappear. I don't know if that helped, but I changed the search backend to something else than Nominatim and then back again. Since then (though I don't know if that was really the "fix") the search box does not disappear (and honestly, this problem was there for some month).

**Comment by kiozen** [comment] 2020-01-07 18:29
Hm, a bit strange. Maybe some peculiar combination with an old configuration file. 

Anyway, as I can't reproduce it I will close the issue for now. If there is new information it can be re-opened again.

**Comment by googol42** [comment] 2020-01-19 11:31
I am just experiencing this issue again.

> Hm, a bit strange. Maybe some peculiar combination with an old configuration file.

Which settings could be causing issues? I can test it, but I would like to reuse most of my config file if possible or avoid reconfiguring everything, respectively.

**Comment by googol42** [comment] 2020-01-19 11:31
@kiozen can you reopen the issue?

**Comment by kiozen** [comment] 2020-01-19 13:04
You can start qmapshack with:

```
qmapshack -c test.cfg
```

This will open a new configuration file without tempering your system-wide one. 

```

The configuration in question is
```
isGeosearchVisible=true
```

**Comment by googol42** [comment] 2020-01-20 08:05
I think I might have found something. I just opened QMapShack and it was loading my map (while the splash screen was shown) and then the geo search did not show. Then I restarted QMapShack and the geo search was there. The Map which was loaded was a 3,3 GB img map. I don't have a SSD so this takes a few seconds. Looks like a race condition.

**Comment by googol42** [comment] 2020-01-20 08:06
I think I might have found something. I just opened QMapShack and it was loading my map (while the splash screen was shown) and then the geo search did not show. Then I restarted QMapShack and the geo search was there. The Map which was loaded was a 3,3 GB img map. I don't have a SSD so this takes a few seconds. Looks like a race condition.

I'll keep an eye on this if I see this behaviour next time a map is loaded.

**Comment by googol42** [comment] 2020-01-20 18:05
I just reproduced it again.

**Comment by kiozen** [comment] 2020-01-23 07:03
I can reproduce it. It's happening each time QMS has to load a Garmin map showing the progress dialog.

**Closed** 2020-02-13 08:20 UTC
Labels: bug

**Comment by Silicomancer** [comment] 2021-08-13 09:51
I get it as well. But I think this happens after a restart of the computer.
