### ISSUE TITLE
Error when opening QmapTools

### ISSUE THREAD

**Issue by Gilbertdelyon** [Maproom/qmapshack#600] opened 2023-04-21 09:07 UTC
W10 - QMS last version (1.16.1)
When I open **QmapTools** I get this message
![image](https://user-images.githubusercontent.com/91057837/233593496-50608371-049b-49f5-99e1-1d3c9a45393b.png)
I have to cancel 4 times before QmapTools to open

Then when I load an image file for referencing I get again the same error. 
I need to cancel 2 times before the map to load

Then again when I load the relative  file.gcp 
I need to cancel  only 1 time.

Then again when I delete the image file
I need to cancel  only 1 time.

Any idea?

**Comment by Gilbertdelyon** [comment] 2023-04-21 09:16
Despite these errors I can launch referencing process and it produces the image file and vrt file,
but during the process I get these errors

Warning 6: driver JPEG does not support creation option tiled
Warning 6: driver JPEG does not support creation option compress
Warning 1: 4-band JPEGs will be interpreted on reading as in CMYK colorspace

**Comment by Gilbertdelyon** [comment] 2023-04-21 09:29
Next step Exporting to jnx
Qmatool is processing the jnx file without any error
The jnx file is perfectly usable (display in QmapShack correctly)

**Comment by wthaem** [comment] 2023-04-23 05:39
@Gilbertdelyon: A while ago I had the same annoying initial error. If I remember well it was caused by a broken initial setting. Try to start QMapTool with a non-existing INI-file like this:

`qmaptool.exe -c  dont_exist.ini`

After closing QMT use the newly written `dont_exist.ini` to run QMT.

**Closed** 2023-04-23 07:08 UTC
Labels: bug

**Comment by Gilbertdelyon** [comment] 2023-04-23 18:51
Yesss, it works! Thank you.
