### ISSUE TITLE
Building Routino Database fails

### ISSUE THREAD

**Issue by rdorsch** [Maproom/qmapshack#604] opened 2023-06-08 21:02 UTC
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
I upgraded to the upcoming Debian 12 (bookworm) and tried to import a new routino file.

I got an error:

```
/usr/bin/planetsplitter --dir=/home/rd/.QMapShack/Routino.nobackup/ --prefix=DE-2023-06-06 --tagging=/usr/share/routino/tagging.xml --parse-only /home/rd/Downloads/germany-230606.osm.pbf

Parse OSM Data [/home/rd/Downloads/germany-230606.osm.pbf]
==============

Reading: Bytes=4120028596 Nodes=384714357 Ways=62781592 Relations=775000Routino Fatal Error (relationsx.c:240): Route relation contains too much data (change FILESORT_VARINT to 32-bits?)

!!! fehlgeschlagen !!!
```

I cannot tell if it is related to the Debian upgrade, the last database build, I did in 2022-08-28.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

It is not clear to me, where I could change FILESORT_VARINT to 32-bits.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

Standard procedure to build a routino database with germany-230606.osm.pbf

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Works as before w/o throwing an error :-)

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

n/a/

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

Url for map database for routino:
http://download.geofabrik.de/europe/germany-230606.osm.pbf

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

There is no crash.

### Desktop
[comment]: # (please complete the following information)

 - OS: Upcoming Debian 12 (bookworm)
 - QMapShack Version:   1.16.1
 - Window Manager:  KDE

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment] 2023-06-09 09:31
This is a duplicate of #601

**Closed** 2023-06-09 09:30 UTC
Labels: bug, duplicate
