### ISSUE TITLE
.fit files from Suunto app have many trackpoints with elevation = 0

### ISSUE THREAD

**Issue by runrun1234** [Maproom/qmapshack#343] opened 2021-03-14 21:00 UTC
[Walking_2021-03-06T11_50_22.zip](https://github.com/Maproom/qmapshack/files/6137540/Walking_2021-03-06T11_50_22.zip)

**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Describe the bug**
.fit files exported from Suunto app have many trackpoints with elevation = 0

**What have you done to circle down the problem?**
I tried to upload this fit file to various online services:
VisuGPX : OK ascent 377 m
Strava : OK ascent 361 m
Training Peaks : OK ascent 361 m
Wikiloc : OK ascent 276 m
Komoot : OK ascent 270 m
Only Garmin Connect is not OK with ascent  1431 m... and I know already what Garmin will say about a Suunto file.

**To Reproduce**
1. Import attached .fit file to QMapShack v1.15.2
2. many trackpoints have elevation = 0 ; result is that total ascent/descent are way too high.

**Expected behavior**
There should be no trackpoint with elevation = 0 in this track.

**Screenshots**
-

**Attachments**
See attached .fit file generated by Suunto app

**Tracebacks**
-

**Desktop (please complete the following information):**
 - Windows 10 64 bits

**Additional context**
-

**Comment by tormet** [comment] 2021-04-12 22:12
OK I took a look at it. I think something like this is more what you have expected ;-)

![image](https://user-images.githubusercontent.com/37560190/114465426-63db5000-9be7-11eb-83c9-5bf2f156dcd1.png)

This is BTW also the result I got if I use some DEM's for Europe or France. Than I got ascend and descent values between 300 and 335m.

**What is the root cause for this problem?**

Technically this  has to do with Record messages, global message number 20. 
So what happens in detail. The following functions are definied in .../fit/serialization.cpp
We call:
_void CGisItemTrk::readTrkFromFit(CFitStream &stream)_

If we then found a Record message, we will call 
_readFitRecord(const CFitMessage &mesg, IGisItem::wpt_t &pt)_

In _readFitRecord() is_ is it (wrongly) expected that the Record message contains an altitude field/value. This is line:
87: _pt.ele = (int) mesg.getFieldValue(eRecordEnhancedAltitude).toDouble();_

But if the Record message does not contain an altitude field, than _mesg.getFieldValue(eRecordEnhancedAltitude)_ will not find one and we will get an invalid _QVariant (QVariant::QVariant())_ as the result from  the _getFieldValue(..)_ call, because the _QMap_ where the fields are stored does not contain a value for the key _eRecordEnhancedAltitude_

In the first fast fix I handle this by setting the elevation to invalid. The screenshot above is made using this fix.

Then while loading  the fit file you will be informed about it:
![image](https://user-images.githubusercontent.com/37560190/114467503-4bb90000-9bea-11eb-8d23-3be474362b1f.png)
If you then select Yes, hiding the invalid points you will get the correct elevation as shown in the first screenshot.

I have to think a little bit more about the right strategy for fixing it. Perhaps the current strategy is good enough.

**Additional information:**
In the example fit file we got this with definition and data messages which looks as follows (CSV format from the FitCVSTool)

```
Definition,3,record,timestamp,1,,position_lat,1,,position_long,1,,,,,,,,,,,,,,,,,,,,,,,
Data,3,record,timestamp,"983962302",s,position_lat,"513964730",semicircles,position_long,"71870849",semicircles,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Data,3,record,timestamp,"983962412",s,position_lat,"513960622",semicircles,position_long,"71884487",semicircles,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

This is in my opinion absolutely valid.  We then  create a fit message which contains no altitude value. Which is what is expected here.
BTW the example fit file contains 24 "Data,3-messages" and due to this we have 24 points with an elevation of 0m. ;-)

**Comment by runrun1234** [comment] 2021-04-13 07:44
Thanks for your effort.
For me marking trackpoint without elevation data as invalid is OK.
(on the other hand it is not mandatory for trackpoints to have elevation data... but if those trackpoints are kept, it will be a nightmare for me to remove them one by one by hand.)

**Comment by tormet** [comment] 2021-04-13 09:45
Thanks for the feedback. 
I think I will go in this direction just marking the elevation as invalid. 
Than one can decide to keep the points or throw it away with **one** click. 

If one keeps the data, currently QMS does not calculate an accumulated elevation change but then on can choose 'Replace elevation by DEM' to get it, if one has the DEM data. So the user has the choice.

In the long run one can also think about changing the algorithm which calculates the accumulated elevation change.
But this is another story ;-)

**Closed** 2021-04-14 18:33 UTC
Labels: bug
