### ISSUE TITLE
garmin fenix5 support?

### ISSUE THREAD

**Issue by csurghi** [Maproom/qmapshack#57] opened 2019-10-27 11:21 UTC
hi 
not sure if this is the right place to ask but anyway.. 
in the guide i read that my garmin fenix5 should appear automatically in the workspace window after connecting it to the usb, but it does not, do you have some advice pls? i would like to use it for displaying  my latest moves.

setup workspace>enable device support is enabled
qms 1.13.2
win 7

thx
PEter

**Comment by kiozen** [comment] 2019-10-27 12:45
If the Fenix can be connected as USB Memory and has a valid GarminDevice.xml QMapShack should be able to list it and to read it's content. AFAIK it's not possible with the Fenix. So this is not a bug. It's is a missing feature. 

As none of the active developers owns a Fenix nor intends to buy one this won't be implemented any time soon. As usual device support has to be provided by those using the device.

**Comment by csurghi** [comment] 2019-10-27 14:39
hi thx for the super fast reply. i unterstand, however it seems that my fenix is shown as usb device and that file is also there (see screenshot).

 

if this wont work is there a possibility to directly link a garmin connect account or a dropbox/local file with gpxs?

 

Peter

**Comment by kiozen** [comment] 2019-10-27 15:30
Are you sure this is USB Memory Storage and not just an MTP device? The Explorer might not make any difference in representing such a device. But it's a huge difference in the protocol.

You can load/store local gpx files with QMapShack. However the device support in QMapShack does a bit more, e.g. write a simplified GPX that does not upset devices. But you can store GPX without extensions, too, achieving a similar result.

BTW next time you file a bug or a feature request please stick to questionnaire of the template. I will probably close all new requests that do not stick to that procedure in the future.

**Comment by anesthesia79** [comment] 2019-10-27 16:43
Hello,
My Garmin Instinct offers "mass storage mode" and "Garmin mode". I tried both settings - device is with both seetings shown in QMS. Also my lost Garmin EPIX was shown in QMS. 

OS: Linux Mint 19.3

**Comment by csurghi** [comment] 2019-10-27 17:03
hi thx for replies. sorry for not following the template. i checked- my fenix5 supports only MTP/"garmin" mode. neither of them works for displaying in QMS. anybody knows some workaround?
do the gpx files need to be added manually to by DB/workspace or can QMS check automatically in some folders?
thx for a great tool!

**Comment by anesthesia79** [comment] 2019-10-27 17:16
You need to load manually. 

https://github.com/Maproom/qmapshack/wiki/DocHandleGpxFiles

**Comment by norbusan** [comment] 2019-12-08 21:29
Just a comment from my side, I am using a Garmin Fenix 5x and here it shows up correctly in qmapshack, fit tracks can be loaded etc.

My guess here is that Mint misses some udev rules to set proper permissions for the current user.

**Comment by csurghi** [comment] 2019-12-08 21:37
hi Norbusan, thx for the reply. So your Fenix contents show directly in QMS? Sorry I didn´t get the second part, what does it mean?:) Peter

**Comment by norbusan** [comment] 2019-12-08 22:16
Hi @csurghi 
yes, it does show up. The second part is about hardware devices that are connect to your computer normally are **not** automatically accessible for a normal user but only the `root` user. The `udev` system has a set of rules that changes the permissions accordingly, so users can access devices.

My **guess** is that your udev does not recognize the Garmin fenix, so it keeps the permissions set so that only root can access it, and thus it will not show up in QMS.

Can you look at the output of `journalctl -f` (to be run as root) or `tail -f /var/log/syslog` when you plug in the device? Is there something shown?

**Comment by norbusan** [comment] 2019-12-08 22:17
Sorry, I cannot check myself now, since I am travelling and don't have the proper cable with me.

**Comment by csurghi** [comment] 2019-12-09 07:21
thx for the reply. this however works only for linux right? I am on Win 7 :/

**Comment by norbusan** [comment] 2019-12-09 08:42
Ah, uuuh, sorry yes, on Windows I have no idea whatsoever ... not sure whether this can actually work

**Comment by kiozen** [comment] 2020-04-10 10:21
As this issue is older than 6 months I close it for now.

**Closed by kiozen** 2020-04-10 10:21 UTC
Labels: enhancement, volunteer wanted
