### ISSUE TITLE
Origin of track coordinates displaced after switching to fullscreen mode and back - Windows os only!

### ISSUE THREAD

**Issue by JFritzle** [Maproom/qmapshack#251] opened 2020-09-02 12:08 UTC
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

[x ] Did you choose a good title?

**Describe the bug**

Origin of track coordinates may be displaced after switching to fullscreen mode and back - Windows operating system only!

**What have you done to circle down the problem?**

Did you compare to previous versions? -> No. No previous versions installed.
Did you check if others have the same problem? -> Yes. No reported issue found concerning same problem.

**To Reproduce**

1. Open QMS in windowed mode - Windows operating system only!
2. Add new track 1
3. Click track 1 in workspace
 -> origin of coordinates of highlighted track is correct (screenshot 1)
5. Hit F11 key and switch to fullscreen mode
6. Add new track 2
7. Hover mouse pointer over track 1 or track 2
 ->  origin of coordinates of highlighted tracks is still correct (screenshot 2)
9. Hit F11 key and switch back to windowed mode
10. Click track 1 in workspace
 -> origin of coordinates of highlighted track is displaced (screenshot 3)
12. Select track 1 in workspace to edit track points
 -> origin of coordinates of all track points to edit is displaced (screenshot 4)

**Expected behavior**

Origin of coordinates should keep correct even when switching between fullscreen mode and windowed mode. 

**Screenshots**

![screenshot 1](https://user-images.githubusercontent.com/62614244/91977664-48d86180-ed23-11ea-904f-25d271afe3cf.jpg)
![screenshot 2](https://user-images.githubusercontent.com/62614244/91977667-4970f800-ed23-11ea-97ed-e3a7a14d25eb.jpg)
![screenshot 3](https://user-images.githubusercontent.com/62614244/91977669-4a098e80-ed23-11ea-9c6a-79cbf67c52c1.jpg)
![screenshot 4](https://user-images.githubusercontent.com/62614244/91977672-4aa22500-ed23-11ea-8a43-c2b993f06446.jpg)

**Attachments**

None

**Tracebacks**

None

**Additional context**

Not reproducible in Linux operating system!

**Comment by wthaem** [comment] 2020-09-02 13:03
Quite some time ago I've seen a similar behavior. Don't remember what was done at that time with this issue. Haven't seen this behavior in the last time.

**Comment by kiozen** [comment] 2020-09-03 08:01
Afaik the issue got dropped when porting all stuff from Bitbucket to Github. 

I can't reproduce it and no one from the Windows community volunteered to fix it. Therefore I will leave it open for half a year. If nothing happens we will drop it again.

**Comment by JFritzle** [comment] 2020-09-03 10:15
Trying to reproduce issue by myself, I noticed an important step was missing.

**It seems following steps are sufficient to reproduce the behavior:**

1. Open QMS in windowed mode - Windows operating system only!.
2. **Maximize window by window decoration's maximize button**.
![maximize](https://user-images.githubusercontent.com/62614244/92098338-67009900-edd9-11ea-90af-ec96dd4c0777.png)
3. Make sure at least one track is visible
4. Hit F11 key and switch to fullscreen mode
5. Hit F11 key and switch back to **maximized** windowed mode
6. Hover mouse pointer over visible track or select track in workspace to edit track points
-> origin of screen coordinates of **highlighted track** or **track points to edit** is displaced

Note:

- Issue does not happen when switching from **non-maximized** windowed mode to fullscreen mode and back.
- Displaced coordinate system becomes recalculated and correct again when switching from maximized windowed mode to non-maximized window mode ...
![normal](https://user-images.githubusercontent.com/62614244/92102202-95cd3e00-edde-11ea-9f0b-d172080561f8.png)
... and back to maximized windowed mode.

**Comment by wthaem** [comment] 2020-09-04 06:26
Can reproduce described issue.
On my snapshot:

* The blue line is the correct track. Moving mouse adds the displaced track. No edit mode when clicking the blue track.
* Edit mode appears when clicking the displaced track, displaced track remains there.
* Changing windows mode as described moves displaced track in edit mode on the correct location of the original track.

**Comment by JFritzle** [comment] 2020-09-04 16:04
I notice a further strange behavior related to maximize button. I suspect the cause is the same as with the displaced tracks.

1. Open QMS in windowed mode and resize window fairly small
![screenshot 5](https://user-images.githubusercontent.com/62614244/92255562-d0180780-eed2-11ea-8d05-91066ee909e6.jpg)
2. Maximize window by window decoration's maximize button
![screenshot 6](https://user-images.githubusercontent.com/62614244/92255587-d908d900-eed2-11ea-8d3b-b116f40f4867.jpg)
3. Hit F11 key and switch to fullscreen mode
![screenshot 7](https://user-images.githubusercontent.com/62614244/92255603-df975080-eed2-11ea-8eb5-390622508179.jpg)
4. Hit F11 key and switch back to maximized windowed mode
![screenshot 8](https://user-images.githubusercontent.com/62614244/92255631-e4f49b00-eed2-11ea-8efc-294dd81b4687.jpg)
 -> Viewable part of map does no longer cover whole drawing area. Even when dragging map by mouse!
5. Leave maximized windowed mode and return to non-maximized windowed mode
 -> Everything becomes correct again (screenshot same as step 1)

Maybe a problem saving/restoring states when switching between normal, maximized and fullscreen window mode (Qt window states Qt::WindowNoState, Qt::WindowMaximized and Qt::WindowFullScreen)?

**Comment by wthaem** [comment] 2020-09-04 18:14
Can reproduce this result, too.

**Comment by kiozen** [comment] 2021-05-08 12:58
As there is no real progress on the topic I close it for now.

**Closed by kiozen** 2021-05-08 12:58 UTC
Labels: bug
