### ISSUE TITLE
Qmapshasck v1.17.0 for Windows

### ISSUE THREAD

**Issue by pelsta** [Maproom/qmapshack#641] opened 2023-10-08 10:41 UTC
Will there be Qmapshasck v1.17.0 for Windows?

**Comment by kiozen** [comment] 2023-10-08 12:40
Duplicate of #636

**Closed** 2023-10-08 12:40 UTC

**Comment by kit-kut** [comment] 2023-10-14 09:50
Did build QMapShack_Install.exe from tag V_1.17.0  
![grafik](https://github.com/Maproom/qmapshack/assets/46577911/b2bf1e56-3380-4cd7-81f8-571db78b29c1)  
Testing seem ok so far, can't reproduce #624 on my system (BRouter1.6.3), only errormessage is shown in case of missing rd5-files.

I had some difficulties when building the installer, seem I have to raise an isse / provide a patch later on.
Followed instructions from https://github.com/Maproom/qmapshack/wiki/BuildWindowsVisualStudio_QMSv116 with my legacy lib sources.  
May I provide the file? How?  

Thank you, Andreas
