### ISSUE TITLE
Multiple selection inside a single GPX

### ISSUE THREAD

**Issue by orsogrigio** [Maproom/qmapshack#252] opened 2020-09-13 14:49 UTC
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Feature requests**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[y ] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

In the work area I can have multiple gpx and I can choose to show/hide either of them with check box

![2020-09-13_16h33_37](https://user-images.githubusercontent.com/35661292/93020714-e6af1480-f5de-11ea-8377-32dca01fa633.png)

But if I have multiple object inside a single gpx I can't choose to show/hide each of them 

![2020-09-13_16h35_20](https://user-images.githubusercontent.com/35661292/93020749-21b14800-f5df-11ea-9145-08fc632c0d54.png)

**Describe the solution you'd like**

I would like to have the selection check box not only for different gpx but also for different object (areas, tracks, waypints) inside a gpx, in order to show/hide single object in the map

![2020-09-13_16h35_20](https://user-images.githubusercontent.com/35661292/93021090-2119b100-f5e1-11ea-8848-81becf10a4da.png)

**Describe alternatives you've considered**

By now I use multiple gpx with only one object (ex. one track for one gpx) so I can enable/disable them in the map. 
I can't for examlpe group object of the same type in one gpx because we are asked many times to show only few object at a time.

**Give a reason why someone else should spend time on that request**

Keep in mind that you ask others to spend their spare time for your request. Convince them
by giving a reason why solving your request has a benefit for them, too. Good reasons are
if you are able to prove

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

Bad reasons are:
* Because software xyz does it
* Because you just want it to have that way
* Because it will solve a very particular problem.

If I have many tracks, like in our cases, this is suboptimal, especially when I must share gpx with other peolple. 
Instead of sharing only one file I must share many files, and If I add some other tracks I must share all files againto minimize mistakes, instead of one new gpx file with all objects up to date.

**Additional context**

Added screenshot inline. Thanks in advance to consider our issue

**Comment by kiozen** [comment] 2020-09-13 17:11
This is a duplicate of Issue #226

**Closed** 2020-09-13 17:11 UTC
Labels: duplicate, enhancement

**Comment by orsogrigio** [comment] 2020-09-13 17:30
Sorry but I don't think it is a duplicate of #226 issue. My issue is relative to single objects under the same gpx that by now I can't choose. See the second and third image and you can see that I can't choose for ex. Track1 and Track2 but I can choose only the parent gpx1. Instead #226 speaks about a facility to multiple select/deselect gpx under the same projects at one time. Absolutley very different things.

**Comment by 7hemas7er** [comment] 2020-09-14 10:23
it's an interesting feature
it's possible reopen?

**Comment by 7hemas7er** [comment] 2020-09-14 10:36
> 
> 
> This is a duplicate of Issue #226
Hi, I don't think it is a duplicate of #226 issue.
but I think it's an interesting feature
it's possible reopen?

**Comment by kiozen** [comment] 2020-09-14 10:43
As with the other ticket it is not very to likely to happen. This request pops up occasionally. The answer is always the same:

* If we would implement this it has to be ok for every case and item. And this will fail. There are collections with a huge amount of items downloadable on the Internet. And users expect these collections to be loaded more or less in a snap. An example is Archie's Caravan and Camping list. This contains over 11000 waypoints. This will make 11000 check boxes to be maintained by the QT subsystem. No way.

* I can not emphasize it often enough: The workspace is not the database. Your problem arises because you are abusing the workspace as a database. It's not the intended use case to load everything in the workspace and then blend out everything but a few items. This is why there is a database and you can select single items to be loaded into the workspace. Keep in mind: every item in the workspace needs to be addressed by each operation. Having loads of items in the workspace puts stress on your system and slows down everything. Don't do it. Store your stuff in the database and load only the stuff you like to have visible into the workspace.

**Comment by 7hemas7er** [comment] 2020-09-14 11:26
I understand.
thanks you
