### ISSUE TITLE
QMapShack-1.17.0.3 crashes with Proxy-Nakarte TSM file

### ISSUE THREAD

**Issue by Phobooky** [Maproom/qmapshack#652] opened 2023-12-07 16:41 UTC
### Describe the bug
[comment]: # 
The last compilation made to resolve an issue has caused an unwanted side effect. The TSM file to get Strava data from the Nakarte Proxy works perfectly for 1.16.1 and 1.17 (QMapShack-1.17.0.1, QMapShack-y 1.17.0.2 builds) but causes QMapShack to crash when zoom-in zoom out with QMapShack -1.17.0.3 when requiring tiles from the Nakarte server.
That is, only QMapShack-1.17.0.3 version crashes.

### What have you done to circle down the problem?
[comment]: # Checked with several versions.

### To Reproduce
[comment]: #  

1. Activate Strava Proxy Nakarte TSM file enclosed.
2. Check all Strava Proxy Nakarte TSM file layes are activated
3. Click on the maps area.
4. Zoom-in, Zoom-out serveral times in a new area not cached.
5. Sudendlye, QMS hangs 

### Expected behavior
[comment]: #  
No hang

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # 

```
<TMS>
  <Title>Nakarte/StravaHeatmap</Title>
  <MinZoomLevel>1</MinZoomLevel>
  <MaxZoomLevel>16</MaxZoomLevel>
<Layer idx="0">
    <Title>Nakarte/StravaHeatmap: All</Title>
    <ServerUrl>https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/%1/%2/%3.png?px=256</ServerUrl>
    <MinZoomLevel>1</MinZoomLevel>
    <MaxZoomLevel>16</MaxZoomLevel>
</Layer>
<Layer idx="1">
    <Title>Nakarte/StravaHeatmap: A pie</Title>
    <ServerUrl>https://proxy.nakarte.me/https/heatmap-external-b.strava.com/tiles-auth/run/purple/%1/%2/%3.png?px=256</ServerUrl>
    <MinZoomLevel>1</MinZoomLevel>
    <MaxZoomLevel>16</MaxZoomLevel>
</Layer>
<Layer idx="2">
    <Title>Nakarte/StravaHeatmap: Bici</Title>
    <ServerUrl>https://proxy.nakarte.me/https/heatmap-external-b.strava.com/tiles-auth/ride/bluered/%1/%2/%3.png?px=256</ServerUrl>
    <MinZoomLevel>1</MinZoomLevel>
    <MaxZoomLevel>16</MaxZoomLevel>
</Layer>
<Copyright>(c) https://www.strava.com/</Copyright>
</TMS>
```

### Tracebacks
[comment]: # 
In the log you can see numerous requests to the Nakarte proxy website. When the zoom is greater than 16, there are errors, but they do not seem to affect versions prior to 1.17.0.3. But in this case, it seems that coinciding with these errors, the application crashes.
```
2023-12-07 17:29:45.792 [debug] Request to "https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66765/48017.png?px=256" failed: "Error transferring https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66765/48017.png?px=256 - server replied: Not Found"
2023-12-07 17:29:45.821 [debug] Request to "https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66766/48017.png?px=256" failed: "Error transferring https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66766/48017.png?px=256 - server replied: Not Found"
2023-12-07 17:29:45.919 [debug] Request to "https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66767/48017.png?px=256" failed: "Error transferring https://proxy.nakarte.me/https/heatmap-external-a.strava.com/tiles-auth/all/hot/17/66767/48017.png?px=256 - server replied: Not Found"
```
### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 11
 - QMapShack Version:   1.17.0.3
 

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by Shark6969** [comment] 2023-12-07 22:17
I am sorry. The problem is a hang. But I have never seen that kind of problem in other versions and it always happens with the new one. If I make zoom in and out in a slow way, QMS hangs too.

**Comment by Phobooky** [comment] 2023-12-07 22:21
I am sorry. The problem is a hang. But I have never seen that kind of problem in other versions and it always happens with the new one. If I make zoom in and out in a slow way, QMS hangs too.

**Comment by Phobooky** [comment] 2023-12-08 08:07
I've been doing tests and I doubt it's a PC performance problem, especially since mine is quite nice. Also, I am not able to reproduce it except in QMS 1.17.03.
The most relevant tests are the following:
I create a new installation of QMS 1.17.03 without any configuration. Just like it comes out of the box.
I configure a single map access path to a folder with a single file that is the TSM of the Nakarte proxy.
I activate the TSM
I zoom in and out and sooner or later, QMS hangs.
There are still many tile search errors. They are of the type "server replied: Not Found" with a zoom of 17 or more that are not accepted as valid in the TSM. That is, if QMS processed it well, it should not make those requests that eventually cause it to hang.
Just before hanging, the log sometimes says:
2023-12-08 8:51:24.976 [debug] 1000023
I don't know if it's relevant.
Although it happens to me without having to force it, with the normal use of zoom-in and zoom-out, to reproduce it, it is done very easily by zooming in and zoom-out a couple of times or three very quickly.

**Comment by Phobooky** [comment] 2023-12-08 08:23
A new clue. I think the problem is in relation to unsuccessful requests of the type "server responded: Not Found".
With the test environment in the previous post, after playing with the zoom in and out for a while, hundreds of errors of this type appear in 1.17.03 and only a few in previous versions.
I give you the complete log after some tests of 1.17.02 that does not crash. Only 15 errors appears:
[Uploading org.qlandkarte.QMapShack.log.txt…]()

**Comment by wthaem** [comment] 2023-12-08 08:48
After many failing attempts now I got a hang, too.

What I did:

* Started QMS with strava.TMS and other world map activated
* Immediately after seeing the map window and not having all tiles drawn I zoomed quickly in and out ===> QMS hangs.
* Can be reproduced

**Comment by Phobooky** [comment] 2023-12-08 09:00
When QMS is hanged, it actually keeps doing things. With the procmon I have seen that it does this when the GUI has not responded for minutes:

![Captura de pantalla 2023-12-08 095720](https://github.com/Maproom/qmapshack/assets/24461946/b7fa77ff-0669-4c32-ba1e-685ffedb76a7)
![Captura de pantalla 2023-12-08 095947](https://github.com/Maproom/qmapshack/assets/24461946/59d6999b-db1b-47d9-ae40-706a7dbd6611)

**Comment by mitxel-m** [comment] 2023-12-09 01:35
Hi all

1. First of all, that server is not a normal server, you ask for a tile, then the server asks for data from strava as a user, and then it serves the tile to you (and I'm not sure if this is authorized by strava). 
Also, all those nakarte server errors will depend very much on the area you visit. If you ask for the Ride layer and there is no ride data then there is no tile, and and apparently it returns an error instead of a default tile. You can check this over the sea.

2. For reference, with the nakarte TMS provided by phobooky,  on linux, QMS 1.16.1, and with a bad internet connection I also get random freezes. So I don't think the changes proposed in # 649 have any influence on this, but I'll keep an eye on it.

3. Please download and try [these TMS files](https://www.dropbox.com/scl/fi/z6k2qlp2sf5c2grmoftjw/Separated_nk.zip?rlkey=yv2jvqsag15m9myyh9sdu1oss&dl=1) instead of yours. The zoom levels are tuned, and are best handled separately. Let us know if you get hangs with them. They work fine for me, if they work fine for you we can close this issue.

Alternatively, if you can determine that the freeze is when QMS waits a long time without receiving a response from ANY server, or handling multi-layer maps, then it might make sense to investigate further, but I would take nakarte out of the equation.

----
P.S. For most cases I don't see any advantage in making a multi-layered TMS, especially when they are redundant (all/run/ride) and you will have to activate/deactivate layers. Even when they contain different themes, I prefer to use them as separate maps, but that's a very personal taste.

**Comment by Phobooky** [comment] 2023-12-09 07:53
I have done some preliminary tests and I am surprised. First of all, I will tell you that although the file I gave you had three layers, I usually only use one at a time. I agree with you that it doesn't make much sense to use more than one at a time. Having said that, after verifying that my file with a single layer continues to hang, I went on to test yours and surprisingly, as I said, I cannot reproduce the problem. That is, if the TSM has three layers even if it only uses one, it hangs. With your files that only have one of those layers, I can't get it to hang.
I take this opportunity to say that I have tried the Strava server by putting my API and the behavior is the same. But I have to do more tests on this topic to be completely sure.

**Comment by Phobooky** [comment] 2023-12-09 16:08
I've been doing more testing regarding Strava TMS with my user cookies. That is, without using the Nakarte proxy.
I confirm that the same behavior occurs. That is, it hangs if the file is multilayer even if only one layer is activated. If I create a file with only one layer, that is, I use a file with only one layer, it does not crash. That is, the same behavior as Nakarte's TSM.

**Comment by kiozen** [comment] 2023-12-10 10:18
Freeze on multi-layer maps? Thought we fixed that in QMS-#547. @wthaem do you build the binaries on the tga 1.17.0 or do you use dev branch?

**Comment by wthaem** [comment] 2023-12-10 13:18
@kiozen: Installer is built using the tag 1.17.0.

**Comment by kiozen** [comment] 2023-12-10 13:45
Ok. Can you make a binary to test latest dev. I think this will solve the issue. If it does I can trigger the next release to avoid running into the same issue over and over again.

**Comment by wthaem** [comment] 2023-12-10 16:04
@kiozen: will be ready tomorrow and published in the release part of my QMS fork.

**Comment by wthaem** [comment] 2023-12-11 07:02
@kiozen, @Phobooky:

You find an installer for the QMS dev version on

[https://github.com/wthaem/qmapshack/releases/tag/dev_ada4ed2](https://github.com/wthaem/qmapshack/releases/tag/dev_ada4ed2)

This commit includes `[QMS-547] Fixed: QMS freezes on zoom when activating multi-layered online maps`

**Comment by Phobooky** [comment] 2023-12-11 08:29
I have to test more deeply, but in the first preliminary tests the results are very good. I have not been able to reproduce the problem. In the afternoon I will continue with more tests. Thank you!!!

**Comment by Phobooky** [comment] 2023-12-11 17:17
For my part, I think I can consider the incident closed. All tests carried out have been carried out to satisfaction. Thank you very much for the work used in the characterization and resolution of the incident.

**Comment by kiozen** [comment] 2023-12-12 06:29
Nice. I will trigger a bugfix release to make this official.

**Closed by kiozen** 2023-12-12 06:29 UTC
Labels: bug
