### ISSUE TITLE
Crash when using tms map

### ISSUE THREAD

**Issue by googol42** [Maproom/qmapshack#626] opened 2023-08-06 08:21 UTC
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

I use various map views (the tabs above the map). One of this views uses the "Waymarked Trails" map. Since 1.17.0 this view QMapShack randomly freezes when I move or zoom the map.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

- I deleted the cached files => didn't help
- Only activated the "Waymarked Trails Hiking" layer => didn't help
- Checked the debug log => no obvious problems found.
- Downgraded to 1.16.1 with which I could _not_ reproduce the crash.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Put the `Waymarkedtrails.tms` to your map folder and reload the maps so that the map is included in the list.
2. Press `Ctrl+t` to create a new map view.
3. Activate the Waymarkedtrails map.
4. (Optional) Disable all layers apart from the `Waymarked Trails Hiking` layer (this reduces the noise in the debug log)
5. (Optional) Close and re-open QMapShack (if you skip this step you have to repeat step 2-4 once QMapShack crashes)
6. Move around and zoom. At some point it will crash.

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

Don't crash :-)

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

The `Waymarkedtrails.tms` file:

```
<TMS>
<Layer idx="0">
<Title>Waymarked Trails Skating</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/skating/%1/%2/%3.png</ServerUrl>
</Layer>
<Layer idx="1">
<Title>Waymarked Trails Mountainbike</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/mtb/%1/%2/%3.png</ServerUrl>
</Layer>
<Layer idx="2">
<Title>Waymarked Trails Cycling</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel> 
<ServerUrl>https://tile.waymarkedtrails.org/cycling/%1/%2/%3.png</ServerUrl>
</Layer>
<Layer idx="3">
<Title>Waymarked Trails Riding</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/riding/%1/%2/%3.png</ServerUrl>
</Layer>
<Layer idx="4">
<Title>Waymarked Trails Hiking</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/hiking/%1/%2/%3.png</ServerUrl>
</Layer>
<Layer idx="5">
<Title>Waymarked Trails Slopes</Title>
<MinZoomLevel>1</MinZoomLevel>
<MaxZoomLevel>19</MaxZoomLevel>
<ServerUrl>https://tile.waymarkedtrails.org/slopemap/%1/%2/%3.png</ServerUrl>
</Layer>
<Copyright>Map data: (c) OpenStreetMap contributors, ODbL CC-BY-SA | Trails by http://www.waymarkedtrails.org/ </Copyright>
</TMS>

```

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Arch Linux
 - QMapShack Version:  1.17.0
 - Window Manager:  i3 version 4.22 (2023-01-02)

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by frankystone** [comment] 2023-08-06 09:24
I think this is a duplicate of #547

What you can do is to split the contents of waymarkedtrails.tms so each entry get its own tms file, like mentioned in the other bugreport. After activating such a single file a freeze of QMS is very rare.

**Comment by kiozen** [comment] 2023-09-15 08:51
is duplicate of #547

**Closed by kiozen** 2023-09-15 08:51 UTC
Labels: bug
