### ISSUE TITLE
Can't return sidebar windows to sidebar (Plasma Wayland)

### ISSUE THREAD

**Issue by yaomtc** [Maproom/qmapshack#691] opened 2024-10-29 00:28 UTC
### Describe the bug

When using Plasma Wayland, and I click the diamond button (this should have a tooltip; a more helpful icon is used on GNOME) on a sidebar widget, a window is created, but there's no button on the window to return it to the sidebar.

### What have you done to circle down the problem?

I searched here a bit and couldn't find anyone mentioning this. I've tested on X11, and it works fine there, the diamond buttons are there on the window. GNOME doesn't have this issue with Wayland, as shown in my comment below.

### Screenshots

On Wayland: 

![Screenshot_20241028_072102](https://github.com/user-attachments/assets/e62060ee-d10c-444c-97de-d2e2ad845cc1)

On X11: 

![Screenshot_20241028_073231](https://github.com/user-attachments/assets/f4d91bdb-1cfc-45b4-b08a-43ac1545dfc6)

### Desktop
[comment]: # (please complete the following information)

 - OS: Arch Linux
 - QMapShack Version:  1.17.1
 - Window Manager:  Plasma 6.2.2 (Wayland)

**Comment by yaomtc** [comment] 2024-10-29 03:18
Just checked GNOME (Wayland) and it does not have this issue. Also, what appears as a diamond button under Plasma has a more helpful "windows" icon under GNOME. So this issue is specific to kwin_wayland (Plasma's default since 6.0)
![Screenshot From 2024-10-28 22-12-55](https://github.com/user-attachments/assets/439d9014-eb6a-416e-bf4e-083ba22e0232)
![Screenshot From 2024-10-28 22-12-27](https://github.com/user-attachments/assets/4f1790c8-ebb0-49ca-81c7-59f21e80836f)

**Comment by kiozen** [comment] 2024-10-29 08:32
These are a dock widgets. A very established element in GUI programming, dating back ages. I think they came up in the Windows 95  era.  Simply grab the widgets toolbar with your mouse (left button kept pressed) and move them either to the left ore the right side of QMapShack's main window (top and bottom work too). You will notice when they are in the focus of the dock are. 

You can even move the dock widgets up and down in the dock area or stack them. By that you can optimize the space of the main window. This is also explained and depicted in the quick help when you add a new map view (strg+t or Menu->View->Add map view)

The eye candy of these dock widget' title bar is subject to your window manager/theme as you already noticed. Some are a bit less cryptic than others. But that is nothing we can influence.

I for instance use only the dock area at the left side. I have two stacks of dock widgets. The top one with the routing and workspace dock widgets. The bottom one with maps, DEM, and the  database dock widgets. All other widgets are hidden as I do not really use them. 

Additionally I moved the tool bar (also a dock widget) to the left side. But you can place it to any other side as you prefer.

**Comment by yaomtc** [comment] 2024-10-29 17:56
@kiozen No:

https://github.com/user-attachments/assets/6a8350c1-efd9-4488-8375-89702adfec51

**Comment by kiozen** [comment] 2024-10-30 07:54
Ok tested it on my machine. It's a Qt/Wayland problem.  These are the reasons why I switch back to X11 within a couple of minutes every time  I give Wayland a try.

There seem to be similar issues for other apps:

https://github.com/dail8859/NotepadNext/issues/451

As suggested in the link I tried it with the Qt6 port of QMapShack inside Weston. It works but the behavior is still quite peculiar and not what you expect. The loose dock widget does not move when grabbed but if you ignore that and move the mouse you can dock it again. 

Let's see if we wait another decade Wayland may get an option.

**Comment by kkarsten62** [comment] 2024-10-30 10:42
I can confirm this behavior for Fedora 40 Workstation with Wayland also.

Bypass is to rename or delete `~/.config/QLandkarte` directory. After restart of QMS you can rearrange/dock the windows again. **But only once - so you have only one try for each window!**

Or stick to X11 as long as you can ...

**Comment by yaomtc** [comment] 2024-10-31 00:44
GNOME lacks this issue, I wonder why? QMapShack is still using Qt even there, right? Not GTK

**Comment by kiozen** [comment] 2024-10-31 09:50
Yes, it's pure QT. No GTK. The dock widget stuff is partly window manager related. That's why the icons differ etc. And the window manger has to send events that the detached widget is now close to the dock widget etc. And these events have to be processed again into some Wayland directives, etc. This seems to be handled by plugins in Qt. There are several for different graphic front ends. As far as I understand the plugin in QT5 has a bug that is kind of fixed in latest versions of Qt6. 

Probably that is the reason why the user experience is so shitty in Wayland. Because several players have to match: Wayland, window manager, GUI tool kit. Any mismatch is a bug and hard to assign to the different projects maintaining these components. For each bug it would need an expert to find out the real root cause. Not going to happen. Therefore progress is slow.  Wayland started in 2008 and is still a pain in the ass in 2024. And it will take even longer to get it as perfect as X11.

**Comment by yaomtc** [comment] 2024-10-31 20:43
OK, I built the qt6 version and the docking/undocking button works on Plasma too!

Here's the PKGBUILD if anyone wants to use it. Not sure if I should submit it to the AUR, considering this will only be useful for a tiny number of people and only until the porting process is done.

https://gist.github.com/yaomtc/211a8e361aba1d6fa60d762906306b29

**Closed** 2024-11-04 07:26 UTC
Labels: bug
