### ISSUE TITLE
POI icon size depends on map zoom level

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#324] opened 2021-02-01 15:26 UTC
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**

**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

Show a few POIs in a map window and change the zoom level. If you zoom out the POI icons are getting smaller and smaller, in the opposite direction they are getting bigger up to the normal size reached at some zoom level.

![icons4](https://user-images.githubusercontent.com/55309218/106478911-0077c800-64aa-11eb-9a1d-a0972eb7a6ff.png)
![icons3](https://user-images.githubusercontent.com/55309218/106478921-01a8f500-64aa-11eb-9865-bec071e4a19c.png)
![icons2](https://user-images.githubusercontent.com/55309218/106478923-01a8f500-64aa-11eb-96c4-d947dc3acfdf.png)
![Icons1](https://user-images.githubusercontent.com/55309218/106478928-040b4f00-64aa-11eb-88bb-3aae205c629b.png)

**What have you done to circle down the problem?**

described in previous step

**To Reproduce**

described with bug description

**Expected behavior**

POI icons should behave like waypoint icons and have one size for all zoom levels of the map.

**Screenshots**

see attached files

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows10
 - QMapShack Version: last pull: Updating 7e394ad5..7e2da710

**Additional context**

BTW: I didn't notice delays in the GUI or blocked GUI.

**Comment by kiozen** [comment] 2021-02-01 17:38
This is not a bug. This is the normal draw behavior for all layers like map, dem and POI. QMapShack scales the current viewport immediately while it starts to render the new one in the background. When done the scaled buffer is replaced by the new one.

If you wait long enough until the rotating wait animation for POIs stops the viewport will show the POIs in the right size.

**Comment by wthaem** [comment] 2021-02-01 19:15
Thanks for the explanation. I found the rotating wait animation but it is quite small and in my case difficult to detect and, more important, it takes an awful lot of time before the window comes to its final layout (approximately a minute or even more). The number of POIs selected: just 6! The online map used is redrawn more or less immediately from the cache when zooming.

When moving the map then there is a much bigger rotating animation, even with 2 circles - much better because clearly visible.

**Comment by kiozen** [comment] 2021-02-02 06:26
The problem is there are no larger circles. see http://ajaxload.info/  But you can play with other animations, maybe you find a better combination.

And yes the loading time is awful long. The number of results does not matter. It's the number of items to parse for results.

Online maps are fast because most of the time they just have to read the cache. And without cache the map starts to render immediately with empty tiles updating frequently when new tiles arrive.

**Comment by kiozen** [comment] 2021-02-05 08:02
I think there is nothing to do, right? Can we close it?

**Closed** 2021-02-05 18:48 UTC
Labels: bug
