### ISSUE TITLE
Online Openstreet maps are not displayed in Qmapshack 1.14.1

### ISSUE THREAD

**Issue by piotrekttdxc** [Maproom/qmapshack#197] opened 2020-06-01 09:23 UTC
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x ] Did you choose a good title?

**Describe the bug**

Online Openstreet maps are not displayed in Qmapshack 1.14.1 

**What have you done to circle down the problem?**

Did you compare to previous versions? What versions? Did you check
if others have the same problem?

I've checked other versions back to 1.13.2, same problem exists. 

**To Reproduce**

Open Qmapshack and activate any of the Open Street maps 

**Expected behavior**

Maps should load. 

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: Windows x64
 - QMapShack Version 1.14.1

**Additional context**

Checked versions back to 1.13.1. Same problem exists.

**Comment by kiozen** [comment] 2020-06-01 10:37
This is a duplicate of ticket #194

**Closed by kiozen** 2020-06-01 10:37 UTC
Labels: bug, duplicate
