### ISSUE TITLE
Crash when inserting a non-autorouted section in a route

### ISSUE THREAD

**Issue by cdoubleplusgood** [Maproom/qmapshack#139] opened 2020-03-28 20:30 UTC
When inserting a point without auto-routing ("O") into a route that is auto-routed otherwise, the program crashes when storing the route "as original" (German: "Ins Original speichern")

I want to create a route from A to D via B and C. There are ways A-B and C-D, but none between B and C. There is a much longer detour from A to D that follows roads, but I don't want to use that way. I want to follow A-B-C-D, following the ways A-B and C-D, but running offroad from B to C. So I want add route sections with auto-routing A-B and C-D, but add "manual" points between B and C.
So in "A" mode I add a route between A and D, which follows the long detour. Still in mode "A" I insert points at B and C. The auto-routed route is now A-B-A-D-C-D. Switch to "O" mode. Insert some point between A and D. Press "Ins Original speichern" (maybe "Save to original" in English?). The program crashes reproducibly on my system.

**Expected behavior**
Should not crash, but save the route, so that I can late save the project (GPX file).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1903 64 bit
 - QMapShack Version 1.14.0

![grafik](https://user-images.githubusercontent.com/51495766/77833066-c8418380-713a-11ea-8996-9e679c867964.png)
![grafik](https://user-images.githubusercontent.com/51495766/77833104-ffb03000-713a-11ea-9226-d649830dfa6c.png)
![grafik](https://user-images.githubusercontent.com/51495766/77833114-240c0c80-713b-11ea-96db-3983cc6edb72.png)

**Comment by kiozen** [comment] 2020-03-29 16:34
I tried to reproduce on my Linux box without success everything works as expected.  Maybe someone with Windows can try.

Btw your report misses information about the router you are using.

As a side note: This will not work as you expect. Because after editing the route QmapShack needs to recalculate the  route. And it will fail for the section that is not routable.

**Comment by wthaem** [comment] 2020-03-29 17:58
Tried this on Wndows10 with BRouter (offline, trekking profile) using approximately the described procedure. No crash.

**Comment by cdoubleplusgood** [comment] 2020-03-29 21:54
Thanks for looking into the issue!
For routing, I use a local Routino database, created from austria-latest.osm.pbf + germany-latest.osm.pbf.
I attached a protocol recorded with Windows Problem Step Recorder (PSR). The crash happens after recording, after clicking "Ins Original speichern".
[CrachQMapShack.zip](https://github.com/Maproom/qmapshack/files/4399852/CrachQMapShack.zip)

**Comment by cdoubleplusgood** [comment] 2020-03-29 21:54
Closed in error, sorry.

**Comment by kiozen** [comment] 2020-03-30 05:43
Can you try the same with BRouter? Does it crash?
Can you try the same with Routino for an other case? Does it crash?

**Comment by kiozen** [comment] 2020-04-08 11:46
any progress here?

**Comment by cdoubleplusgood** [comment] 2020-04-10 19:06
I could not reproduce the problem with brouter online, because auto routing seems not supported with online routers.
I also could find no other location on the map where exactly this problem occurs.
One more note: The crash only happens with "save as original", i.e. only when the route was already saved and edited then.

However, I found a location where the route with both auto-routed and straight sections becomes altered when I press "save as original". See attached pictures.

![ksnip_20200410-210415](https://user-images.githubusercontent.com/51495766/79016375-13ae5580-7b6f-11ea-82ef-0943eb497be8.png)
![ksnip_20200410-210458](https://user-images.githubusercontent.com/51495766/79016386-1741dc80-7b6f-11ea-9a4f-9759249e41f2.png)

**Comment by kiozen** [comment] 2020-04-13 08:32
BRouter can be installed and used as local router. In that case It can do routing on-the-fly. 

But never the less you will and up in what I already mentioned on my first post and you observed yourself: The route is recalculated when saved and you manual mitigation is lost. Works only with tracks, not with routes.

Most likely the crash happens in the Routino library. But without a debug build and a traceback no one can tell.

**Comment by kiozen** [comment] 2020-04-19 12:21
I will close the issue. It's not a general bug to be reproduced. Most likely it's part of the Routino library.

**Closed by kiozen** 2020-04-19 12:21 UTC
Labels: bug
