### ISSUE TITLE
Building on Ubuntu 20.04, missing FindPROJ4.cmake and  FindQuaZip5.cmake files

### ISSUE THREAD

**Issue by jimlienhart** [Maproom/qmapshack#334] opened 2021-02-21 21:52 UTC
**Important Notice:**

**Do not delete any of the sections. Read what is requested. _Replace(!)_ the instructions by your _answer(!)_. Bug reports that are not properly filed might be closed without further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do you think someone else would understand what's fixed or done from your title? Does it really name the real topic of the issue?

**Describe the bug**

Following the build instructions for Ubuntu (20.04), I get:
     CMake Error at CMakeLists.txt:170 (find_package):
     By not providing "FindPROJ4.cmake" in CMAKE_MODULE_PATH this project has
     asked CMake to find a package configuration file provided by "PROJ4", but  
    CMake did not find one.

and after fixing that

    CMake Error at CMakeLists.txt:173 (find_package):
    By not providing "FindQuaZip5.cmake" in CMAKE_MODULE_PATH this project has  
    asked CMake to find a package configuration file provided by "QuaZip5", but
    CMake did not find one.

**What have you done to circle down the problem?**

Solved it by
    cp ../QMapShack/msvc_64/cmake/FindPROJ4.cmake  ../QMapShack/cmake/Modules
    cp ../QMapShack/msvc_64/cmake/FindQuaZip5.cmake  ../QMapShack/cmake/Modules

**To Reproduce**

**Expected behavior**

**Screenshots**

**Attachments**

Can you provide an example file to trigger the problem?

**Tracebacks**

If QMapshack crashes the fastest way to get help is a backtrace. We are
aware that it's not that easy to record one. However if you provide one
chances are good to have it solved very fast. If the problem can't be
reproduced on the developer's environment we will sooner or later request
a traceback.

For Linux see:
https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux

For Windows it would need a debug build and running QMapshack in Visual Studio.

**Desktop (please complete the following information):**

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version [e.g. 1.13.1]
 - Window Manager [e.g. KDE, GNOME]

**Additional context**

**Comment by kiozen** [comment] 2021-02-22 06:23
This is a duplicate of issue #291

**Closed** 2021-02-22 06:38 UTC
Labels: bug, duplicate
